GSSAPI="BASE"  # This ensures that a full module is generated by Cython

from gssapi.raw.cython_types cimport *
from gssapi.raw.names cimport Name
from gssapi.raw.oids cimport OID

from gssapi.raw.misc import GSSError
from gssapi import _utils

from posix.types cimport uid_t

cdef extern from "python_gssapi_ext.h":
    OM_uint32 gss_localname(OM_uint32 *minor,
                            const gss_name_t name,
                            const gss_OID mech_type,
                            gss_buffer_t localname) nogil

    int gss_userok(const gss_name_t name,
                   const char *username) nogil

    OM_uint32 gss_authorize_localname(OM_uint32 *minor,
                                      const gss_name_t name,
                                      const gss_name_t user) nogil

    OM_uint32 gss_pname_to_uid(OM_uint32 *minor,
                               const gss_name_t name,
                               const gss_OID mech_type,
                               uid_t *uid_out) nogil


def localname(Name name not None, OID mech=None):
    """Get the local name for a GSSAPI name.

    This method determines the local name associated with a GSSAPI
    name, optionally for a given mechanism.

    Args:
        name (Name): the GSSAPI name to map to a local name
        mech (~gssapi.OID): the mechanism to use for the mapping
            (or None for the default)

    Returns:
        bytes: the local name

    Raises:
        ~gssapi.exceptions.GSSError
    """
    cdef gss_OID m = GSS_C_NO_OID
    if mech is not None:
        m = &mech.raw_oid

    cdef gss_buffer_desc output = gss_buffer_desc(0, NULL)

    cdef OM_uint32 maj_stat, min_stat

    with nogil:
        maj_stat = gss_localname(&min_stat, name.raw_name, m, &output)

    if maj_stat == GSS_S_COMPLETE:
        py_output = (<char*>output.value)[:output.length]
        gss_release_buffer(&min_stat, &output)
        return py_output
    else:
        raise GSSError(maj_stat, min_stat)


def userok(Name name not None, username not None):
    """Determine whether a GSSAPI name is authorized to act as a local user.

    This method determines whether a given GSSAPI name is authorized
    to act as the given local username.  This is a simple wrapper
    around :func:`authorize_localname` that only supports system
    usernames as local names.

    Args:
        name (Name): the GSSAPI name to check
        username (Union[bytes, str]): the local username to check against

    Returns:
        bool: whether or not the name is authorized to act as the user
    """
    cdef int res

    if isinstance(username, str):
        username = username.encode(_utils._get_encoding())

    cdef char *c_username = username

    with nogil:
        res = gss_userok(name.raw_name, c_username)

    return res == 1


def authorize_localname(Name name not None, Name user not None):
    """Determine whether a GSSAPI name is authorized to act as a local name.

    This method determines whether a given GSSAPI name is authorized
    to act as the given local name.

    Args:
        name (Name): the mechanism name to check
        user (Name): the local name to check against

    Returns:
        bool: whether or not the name is authorized

    Raises:
        ~gssapi.exceptions.GSSError
    """
    cdef OM_uint32 maj_stat, min_stat

    with nogil:
        maj_stat = gss_authorize_localname(&min_stat, name.raw_name,
                                           user.raw_name)

    if maj_stat == GSS_S_COMPLETE:
        return True
    else:
        raise GSSError(maj_stat, min_stat)


def pname_to_uid(Name name not None, OID mech=None):
    """Get the local UID for a GSSAPI name.

    This method determines the local UID associated with a GSSAPI
    name, optionally for a given mechanism.

    Note:
        This function is not available on Windows.

    Args:
        name (Name): the GSSAPI name to map to a local UID
        mech (~gssapi.OID): the mechanism to use for the mapping
            (or None for the default)

    Returns:
        int: the local UID

    Raises:
        ~gssapi.exceptions.GSSError
    """
    cdef gss_OID m = GSS_C_NO_OID
    if mech is not None:
        m = &mech.raw_oid

    cdef uid_t uid_out
    cdef OM_uint32 maj_stat, min_stat

    with nogil:
        maj_stat = gss_pname_to_uid(&min_stat, name.raw_name, m, &uid_out)

    if maj_stat == GSS_S_COMPLETE:
        return uid_out
    else:
        raise GSSError(maj_stat, min_stat)
