GSSAPI="BASE"  # This ensures that a full module is generated by Cython

from gssapi.raw.cython_types cimport gss_buffer_t

cdef extern from "python_gssapi_ext.h":
    gss_buffer_t GSS_C_ATTR_LOCAL_LOGIN_USER


# Export the attribute name constant as a Python bytes object.
# This can be used with RFC 6680 get_name_attribute/set_name_attribute
# to retrieve or set the local login username for a GSSAPI name.
ATTR_LOCAL_LOGIN_USER = (<char*>GSS_C_ATTR_LOCAL_LOGIN_USER.value)[
    :GSS_C_ATTR_LOCAL_LOGIN_USER.length]
